apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  strategy:                 ## ====================================================
    type: RollingUpdate     ## Added for rolling update strategy but it is default
    rollingUpdate:          ## ====================================================
      maxUnavailable: 1     ## max pods can be unavailable during update
      maxSurge: 1           ## max pods can be created above desired pods
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ibrahimmintal/k8s-node-app:latest
        ports:
        - containerPort: 3000
